# Generated by Django 4.2.7 on 2025-11-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.IntegerField(),
        ),
    ]
